// <auto-generated />
using System;
using Fiap.Web.Trafego.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Fiap.Web.Trafego.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240628012552_Relacionamentos")]
    partial class Relacionamentos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fiap.Web.Trafego.Models.Cruzamento", b =>
                {
                    b.Property<int>("CruzamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CruzamentoId"));

                    b.Property<string>("Rua1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("Rua2")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.HasKey("CruzamentoId");

                    b.HasIndex("Rua1", "Rua2")
                        .HasDatabaseName("IDX_RUAS");

                    b.ToTable("CRUZAMENTO", (string)null);
                });

            modelBuilder.Entity("Fiap.Web.Trafego.Models.HorarioPico", b =>
                {
                    b.Property<int>("HorarioPicoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HorarioPicoId"));

                    b.Property<int>("CruzamentoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("HoraInicio")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("HoraTermino")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("HorarioPicoId");

                    b.HasIndex("CruzamentoId");

                    b.ToTable("HORARIOPICO", (string)null);
                });

            modelBuilder.Entity("Fiap.Web.Trafego.Models.Previsao", b =>
                {
                    b.Property<int>("PrevisaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrevisaoId"));

                    b.Property<int>("CruzamentoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("Hora")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("MelhorAlternativa")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("NumeroCarros")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("PrevisaoId");

                    b.HasIndex("CruzamentoId");

                    b.ToTable("PREVISAO", (string)null);
                });

            modelBuilder.Entity("Fiap.Web.Trafego.Models.Registro", b =>
                {
                    b.Property<int>("RegistroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegistroId"));

                    b.Property<int>("CruzamentoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("HoraAbertura")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("HoraFechamento")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("NumeroCarros")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("RegistroId");

                    b.HasIndex("CruzamentoId");

                    b.ToTable("REGISTRO", (string)null);
                });

            modelBuilder.Entity("Fiap.Web.Trafego.Models.HorarioPico", b =>
                {
                    b.HasOne("Fiap.Web.Trafego.Models.Cruzamento", "Cruzamento")
                        .WithMany()
                        .HasForeignKey("CruzamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cruzamento");
                });

            modelBuilder.Entity("Fiap.Web.Trafego.Models.Previsao", b =>
                {
                    b.HasOne("Fiap.Web.Trafego.Models.Cruzamento", "Cruzamento")
                        .WithMany()
                        .HasForeignKey("CruzamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cruzamento");
                });

            modelBuilder.Entity("Fiap.Web.Trafego.Models.Registro", b =>
                {
                    b.HasOne("Fiap.Web.Trafego.Models.Cruzamento", "Cruzamento")
                        .WithMany()
                        .HasForeignKey("CruzamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cruzamento");
                });
#pragma warning restore 612, 618
        }
    }
}
